<?php

namespace App\Services;

class Industries
{
    public static function All(): array
    {
        return [
            'AGRICULTURE' => 'AGRICULTURE',
            'FISHING' => 'FISHING',
            'MINING AND QUARRYING' => 'MINING AND QUARRYING',
            'MANUFACTURING' => 'MANUFACTURING',
            'ELECTRICITY, GAS, AND WATER SUPPLY' => 'ELECTRICITY, GAS, AND WATER SUPPLY',
            'CONSTRUCTION' => 'CONSTRUCTION',
            'WHOLESALE AND RETAIL TRADE' => 'WHOLESALE AND RETAIL TRADE',
            'HOTELS AND RESTAURANTS' => 'HOTELS AND RESTAURANTS',
            'TRANSPORT, STORAGE, AND COMMUNICATION' => 'TRANSPORT, STORAGE, AND COMMUNICATION',
            'FINANCIAL INTERMEDIATION' => 'FINANCIAL INTERMEDIATION',
            'REAL ESTATE, RENTING, AND BUSINESS ACTIVITIES' => 'REAL ESTATE, RENTING, AND BUSINESS ACTIVITIES',
            'PUBLIC ADMINISTRATION AND DEFENSE' => 'PUBLIC ADMINISTRATION AND DEFENSE',
            'EDUCATION' => 'EDUCATION',
            'HEALTH AND SOCIAL WORKER' => 'HEALTH AND SOCIAL WORKER',
            'OTHER COMMUNITY, SOCIAL AND PERSONAL SERVICE ACTIVITIES' => 'OTHER COMMUNITY, SOCIAL AND PERSONAL SERVICE ACTIVITIES',
            'ACTIVITIES OF PRIVATE HOUSEHOLDS AS EMPLOYERS...' => 'ACTIVITIES OF PRIVATE HOUSEHOLDS AS EMPLOYERS...',
            'EXTRA-TERRITORIAL ORGANIZATIONS AND BODIES' => 'EXTRA-TERRITORIAL ORGANIZATIONS AND BODIES',
        ];
    }
}
